server:
  port: 8761

spring:
  application:
    name: edu-eureka-boot

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      #其他服务要注册到Eureka需要访问的地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
